### ISSUE TITLE
Pinguço

### ISSUE THREAD

**Issue by edn9** [stark/Color-Scripts#15]
Based on elfman, this was my first time doing it, hope you like it. :)
https://pastebin.com/pqnrRCUi
![image](https://user-images.githubusercontent.com/28832216/48662078-8e02a500-ea63-11e8-8bb0-dac79d93e06a.png)
![image](https://user-images.githubusercontent.com/28832216/48662080-9b1f9400-ea63-11e8-9c8d-33e70967d206.png)

**Comment by stark** [comment]
Looks great ! Thank You for your contribution !
