### ISSUE TITLE
Pipes

### ISSUE THREAD

**Issue by Foggalong** [stark/Color-Scripts#2]
Is there a way to keep the scripts up to date? pipes.sh has changed hands and received a few fixes since the version included in this repo. There are also a few more scripts now maintained [in the same place](https://github.com/pipeseroni)

**Comment by stark** [comment]
Sure, why not. Please **Feel Free** to fork this repo add/update the respective script(s) and also update their related preview (they are in the directory name: preview) and make a Pull request.

And Thank You for the link, I wasn't aware of this repo.
